import type { Condition } from "../engine/types";

/**
 * Weather is generated by a seeded Markov chain so conditions correlate
 * day-to-day (heatwaves and rainy spells persist rather than flickering).
 * Rows sum to 1; columns follow CONDITION_ORDER.
 */
export const CONDITION_ORDER: readonly Condition[] = [
  "heatwave",
  "sunny",
  "partly",
  "cloudy",
  "rainy",
  "cold",
];

// transition[from] = weights over CONDITION_ORDER
export const WEATHER_TRANSITION: Record<Condition, readonly number[]> = {
  //              heat  sunny partly cloud rainy cold
  heatwave: [0.45, 0.35, 0.12, 0.05, 0.02, 0.01],
  sunny: [0.12, 0.45, 0.25, 0.1, 0.05, 0.03],
  partly: [0.05, 0.25, 0.35, 0.2, 0.1, 0.05],
  cloudy: [0.02, 0.12, 0.26, 0.3, 0.2, 0.1],
  rainy: [0.01, 0.08, 0.18, 0.28, 0.33, 0.12],
  cold: [0.02, 0.1, 0.15, 0.23, 0.2, 0.3],
};

/** Neighbouring conditions used when a forecast is "off by one". */
export const CONDITION_NEIGHBORS: Record<Condition, readonly Condition[]> = {
  heatwave: ["sunny"],
  sunny: ["heatwave", "partly"],
  partly: ["sunny", "cloudy"],
  cloudy: ["partly", "rainy"],
  rainy: ["cloudy", "cold"],
  cold: ["cloudy", "rainy"],
};

export const WEATHER_LABEL: Record<Condition, string> = {
  heatwave: "Heatwave",
  sunny: "Sunny",
  partly: "Partly Cloudy",
  cloudy: "Cloudy",
  rainy: "Rainy",
  cold: "Cold",
};

export const WEATHER_ICON: Record<Condition, string> = {
  heatwave: "🔥",
  sunny: "☀️",
  partly: "⛅",
  cloudy: "☁️",
  rainy: "🌧️",
  cold: "❄️",
};
